APP = $(notdir $(CURDIR))

NEURON_IMPL_H = $(EXTRA_SRC_DIR)/my_models/implementations/iaf_psc_exp_nestml_impl.h
SYNAPSE_DYNAMICS = $(NEURON_DIR)/neuron/plasticity/synapse_dynamics_static_impl.c

include ../extra.mk